### ISSUE TITLE
Kubos Repo Re-Org

### ISSUE THREAD

**Issue by CatGarab** [kubos/kubos#33]
The question of how APIs and services should be arranged within the repo has come up.

Option 1: category/specific-device/{api, service}

```
adcs
    imtq
        imtq-api
        imtq-service
   mai
       mai-api
       mai-service
core
    comm-service
    file-transfer-service
    shell-service
    telemetry-database-service
eps
    nanopower
        nano-api
        nano-service
radio
    trxvu
        trxvu-api
        trxvu-service
    duplex-d2
        d2-api
        d2-service
    simplex-stx3
        stx3-api
        stx3-service
```

Option 2: {apis, services}/category?/specific-device

```
apis
    adcs
        imtq-api
        mai-api
    eps
        nano-api
    radio
        trxvu-api
        d2-api
        stx3-api
services
    adcs
        imtq-service
        mai-service
    core
        comm-service
        file-transfer-service
        shell-service
        telemetry-database-service
    eps
        nano-service
    radio
        trxvu-service
        d2-service
        stx3-service
```

**Comment by jacoffey3** [comment]
I like the idea of separating out apis and services better, because there are times when something won't fit cleanly into a single subsystem (the nano is actually a battery _and_ an eps, for instance).

It could also be helpful to reduce the number of top level directories. 

I like the idea of bundling all services together, because it clearly defines "everything in this folder is a process that runs".

We can also then add an "applications" folder to the top level. Otherwise, where would you put an application that uses both the EPS and the Radio? Or an application that uses core services and the adcs? That structure will give those a place and allow us to name them by purpose, rather than what hardware they are related to.

**Comment by CatGarab** [comment]
Final conclusion: 
- Top-level folders `applications`, `services`, `apis`
- Within them will be the various APIs in a flat structure (rather than grouped by category)
- Hardware-specific folders should be prefixed with the manufacturers name (isis, nsl, etc)

```
apis
        gomspace-p31u-api
        isis-imtq-api
        isis-trxvu-api
        mai-mai400-api
        nsl-d2-api
        nsl-stx3-api
services
        comm-service
        file-transfer-service
        gomspace-p31u-service
        isis-imtq-service
        isis-trxvu-service
        mai-mai400-service
        nsl-d2-service
        nsl-stx3-service
        shell-service
        telemetry-database-service
```
