### ISSUE TITLE
SDK Planning 

### ISSUE THREAD

**Issue by jacoffey3** [kubos/kubos#334]
Currently, our SDK is in a state where it can be quite difficult to get started using KubOS. We require you to run on a board, and the SDK interface environment can require a lot of setup before giving a clean and quick interface to your code. 

This issue is an effort to identify the ideal intro developer experience, from first interaction with KubOS to beginning developing on hardware for a mission, to identify and define what we are currently lacking. 

Intro User Story:
============

Step 1: Test/Interact with KubOS Services
-----------------------------------------
- Install `kubos` command line tool. 
- Create a `config.toml` for your desired collections of middleware services
- Command line tool then downloads, builds, and runs those services based on the config file
- Start building mission applications to understand how to interact with the system using GraphiQL, the application api, and the file/shell clients
  - Start with example app (python or rust)
  - Go through tutorial to incorporate monitor service
  - Build in new command line arguments 
- Spec out any hardware integrations needed for your mission, and start on the payload/hardware services for them (maybe interacting with the hardware directly from your laptop prior to integrating it with the OBC) 
  - Start with kubos-service crate/package
  - Spec out what you want the payload to do
  - Use the GraphiQL to send mutations and queries to test out the schema and test the hardware service 
  - Interact with your created service from a mission application

Step 2: Obtain Board with KubOS
---------------------------------

  - Board from partnered vendor: 
    - Preloaded with latest KubOS release preconfigured
  - Board bought elsewhere:
    - Find all the things you need easily and quickly from a new landing page for KubOS 
      - Latest version
      - Builds for OBCs
      - Links to docs
        - Walkthrough for configuring, building, and installing latest KubOS release
        - Tutorial for installing pre-built “off the shelf” versions for bare OBCs so users of the standalone OBC doesn’t have to build KubOS first thing

Step 3: Setup Hardware Interface Environment
----------------------------------------------
- Install vagrant SDK 
- What other things?
  - Set up shared folders
  - Set up remote development environment (SSH access to VM from local editor)
  - Windows Users: Do windows things...

Step 4: Connect to board
-------------------------
- Plug in FTDI USB cable into debug serial port of device
  - See a “sign of life” that the systems are connected
  - Log output starts scrolling?
  - Intro message? 
- Set up ethernet, if available

Step 5: Test Developed Mission Apps and Hardware Services on the board
-------------------------------------------------------------------------
- Shell into board and test that hardware is connected 
- Build and run on the board
- See output in the SDK 

Step 6: Develop Flight Mission Applications
-------------------------------------------
- Read documentation on the recommended way to structure a mission in KubOS
- Take the previous mission application(s) and augment them to do the desired operations for the mission
- Make new mission apps that manage onboard systems and operations
- Develop them locally, and test on the board
- Figure out what mutations/queries to put in it with the GraphiQL GUI
- Interact with the payload service and other services
- Test them and create flight ready versions

Step 7: Integrate with Mission Control System (Such as Major Tom)
---------------------------------------------
- Commanding
- Visualize telemetry
- Downlink/Uplink files
- Shell
- Pass operations
- Recovery operations

Step 8: Long Term Testing
--------------------------
- Hardware checkout
- Vibe testing
- TVac
- Day in the life
- Practice passes
- Long term bench testing
- Review results

Step 9: Prepare for Launch
--------------------------
- Read documentation on required pre-launch steps to get KubOS flight ready
- Flight build of KubOS
- Prepare fallbacks
- Ensure all partitions are up to date
- Clear Logs
- Clear deployed flag
- Hardware prep process
- Have a way to tag the build number exactly for reference for years to come (for instance, should be able to be reproduced for the mission life of the satellite) 
- Binary sha256 & build date baked into binaries? This could also be solved by app metadata

**Comment by jacoffey3** [comment]
What's Needed?
=====================

Kubos CLI 
----------
Tool for installing KubOS Middleware and doing preliminary development outside the vagrant VM. This allows users to interact with Middleware and start developing/testing mission apps and hardware/payload services without having to worry about hardware or a full VM. It can read a kubos config toml to see what services they want and how they want them running/configured, then download/build/run those services for you (or stop them for you). 

The Vagrant VM would be more oriented around hardware interaction, so when you move to hardware, you can have the CLI in the VM ingest your toml file to do the build for you. 

Minimum functionality for the CLI (would greatly appreciate input here): 
- Install on your machine
- `kubos install config.toml`
  - Processes your toml, downloads the repo, and builds the services you have configured
  - Installs the KubOS packages for you:
    - application apis
    - service packages
    - comm service library
    - etc
- `kubos start` 
  - Runs the installed services for you, and shows their log output
  - If there isn't hardware available for a hardware service, it exempts that service and notifies you
- `kubos stop` 
  - Stops any running KubOS middleware services 
- `kubos create`
  - pulls the example mission applications or hardware services in either Python or Rust (or any future supported language) 
- `kubos app ...`
  - commands for running, installing, versioning, uninstalling, whatever you need to do with mission applications and the interaction with the application service 
- What else? 

Logs feed
---------
Live feed of logs scrolling automatically 
  - Optionality for:
    - Kernel logs
    - Kubos Service logs
    - App logs
    - Error logs
  - Can run in more than 1 window to allow for different log views

Documentation (always...)
--------------------------
We need to do another documentation re-org, but also we need to highlight these things in the next documentation effort to help new users and users that are doing preparation for missions. 
- Tutorial for configuring/building/flashing KubOS linux
- Install the vagrant SDK and connect to a board
- Typical mission architecture in KubOS
  - Tutorial for recommended mission apps for a typical mission
    - Deployment app
    - Housekeeping apps
      - KubOS Middleware App
      - Power management
      - Threshold monitoring
      - Telemetry Collection/storage
      - Health and Status beacon generation
    - Payload/Operations app
    - Radio monitoring app
- Flight ready KubOS checklist
- Walkthrough for recommended mission prep
  - What do I need to do to KubOS before launch?

**Comment by damons** [comment]
I like the idea of a CLI to manage KubOS as the framing for overall interactions.  This seems to have become a responsible practice when designing frameworks.  We see this with Node, Keybase, and git, for example.  It also builds our ontology that we use to communicate with each other (an argot).  

With a CLI that has a clearly defined ontology, one could envision the next phase of development after the working CLI:  A GUI for desktop and mobile that represents the same functionality while also giving new users new channels for adoption.

I know that we think of Major Tom as the Web view into telemetry.  With the addition of the CLI to configure KubOS, would it make sense to envision wrapping the CLI into a Major Tom app that performs the same duties and also enables "pushes" of KubOS instances/toml's to hosted environments--Kubos' Major Tom infrastructure or even third parties that provide the same services using KubOS's protocols? 

The command hierarchy described in this issue might consider a meta-level up.  For example:

`$ kubos mission new {mission_name} --type {terrestrial|orbital|etc.}`

This would create an entry for a new mission with a given name.  A mission needs a Ground Control and a Satellite (along with many other things, I'm sure).  The type for the mission could be terrestrial if this is a test flight or something.  I don't know.  I'm just making this up as I go.  :)  But, let's consider the next step, which would be to create a satellite entry we'd use for our mission:

`$ kubos satellite new --type {beagle|pi|isis|etc} --port {/dev/USB0|tcp:10.0.0.1:3030|etc.}  {satellite_name}`

Now we have a cubesat to attach to our mission.  So, let's provision it into a mission:

`$ kubos mission provision satellite {mission_name} {satellite_name}`

This command is a bit longer because more than one type of thing can be provisioned in a mission.  For example, one could provision a specific ground control that is different from the default.  The default could be a basic communications process that KubOS provides that does basic comms to a simulated or test satellite (environment).  When moving out of development, one would need a real ground control.

`$ kubos control new {ground_control_provider}`

`$ kubos mission provision control {mission_name} {ground_control_provider}
  
where `control` in this case means ground control, or rather, the communications provider to the satellite and telemetry.  It could default to `localhost` when running a ground control station process locally for demo purposes, or it could be pointed at majortom.kubos.com when a KubOS developer wants to use hosted services (i.e., Major Tom).

**Comment by jacoffey3** [comment]
@damons I would want to focus primarily on the provisioning of a single satellite, and worrying about the larger mission needs later. The Ground Station interface especially is almost always entirely unique. Once we have some solid commercial ground station providers that we can base that part around, it'll be much easier. 

I like the idea of wrapping the CLI into Major Tom though, especially for a flatsat-like environment. You could add a test satellite in Major Tom with a `config.toml`, and we could spin up an ec2 node and run it for you:
 
`$ kubos satellite new --config {config.toml} --simulator {NOS3,other?} --gateway {majortom} {satellite_name}`

You can interact with it, submit mission apps, run and see their output all from Major Tom, or you could run it locally and get the same interface.

**Comment by damons** [comment]
Focusing on a single satellite is just fine.  It makes things simpler to begin with, and I like that.  Also, it eliminates potentially duplicated words in the CLI.  `kubos` would just initially assume a configuration for one device, and setting the name, parameters, and other details would simply be more `--{command}` -like options. 

I also like the idea of having the --gateway as an option.

**Comment by damons** [comment]
More thoughts:

If one considers the hosting of applications and services, like what we see today with hosted Web applications and API end-points, the satellites themselves are essentially co-located servers in space, and many of the same concepts apply.  I don't mean to jump all the way to hosted Web servers in space.  I'm only mentioning this because whatever we choose to do now should be somewhat compatible with potential future directions (i.e., hosted apps in space).  To be clear, something like the following would be compatible with already successful hosting environments that are proven to work.  We shouldn't avoid considering such concepts when designing our basic CLI.  

Hosting providers today, e.g., Dreamhost etc., offer on-demand compute services by providing their users with lists of images of varying sizes and configurations available to be cloned into volumes that can be booted into specific instances of servers of varying capabilities chosen by users.

If I understand correctly, there once was an effort to wrap the management of VMs, Vagrant, etc., into the KubOS scripts so things can all be done in one place.  This apparently was discontinued?  I may be wrong about what was done as I'm basing my assumption on a vague memory of a conversation from weeks ago.

I wouldn't suggest recreating that.  Instead, I'm wondering if there's a smaller, faster way to bootstrap a tiny-yet-extensible image to optimize the adoption and the out-of-the-box experience.

`$ kubos volume --image {kubos_source_image} --size {size_in_mega/gigabytes} {volume_name}`

creates a new volume from a KubOS image with a specific size in gigabytes.  Volumes which can be resized dynamically will likely be essential to minimize image downloads, etc.

`$ kubos  provision volume  {volume_name}`

This would use the local system to provision an operating system to our satellite (likely a virtual one as part of the out-of-the-box experience).  Also, this could open the path towards future provisioning that is non-local by changing the command to:

 `$ kubos gateway provision volume {ground_control_name} {satellite_name} {volume_name}`

Other concepts:

`$ kubos gateway query {gateway_name|default:localhost|majortom.kubos.com} {satellite_name} '{query_string}'`

to do a query of satellite data by way of a specific gateway.  One could imagine `mutate` in addition to `query`.

**Comment by marshall** [comment]
One requirement that was assumed here but not called out explicitly:

* The ability to flash bare OBCs with a pre-built KubOS image/volume (per @damons suggestion around volumes). This would include integrating the download of pre-built KubOS images for supported hardware into the SDK

I really enjoyed @damons take on going a meta-level up and defining potentially multiple satellites in terms of "mission". Making the workflow simple for only 1 satellite could be easy also, by just making that the default mode of operation for all commands. 

Agreed with @jacoffey3 though that the ground side of this is a bit out of scope for the Kubos SDK, which should primarily be focused on the developer experience of writing, testing, and final deployment of flight software before operations.

**Comment by jacoffey3** [comment]
An unstated requirement:
- Be able to interact with hardware for service development purposes (for instance, communicating with a subsystem prior to integrating it with the rest of the bus)

**Comment by jacoffey3** [comment]
Questions that need to be answered: 

- How do we package the kubos services and libraries? 
- What environment do we need to run the background services in? 
- What level of "sandboxing" is required? 
  - How do we achieve it?

**Comment by jacoffey3** [comment]
We're looking for more input! https://github.com/kubos/kubos/issues/352
