### ISSUE TITLE
Get rid of run level reserved arg for mission apps

### ISSUE THREAD

**Issue by jacoffey3** [kubos/kubos#353]
Run levels encourage apps to basically be 2 entirely separate apps in a single file, and cause there to be cases where command line args are necessary for one level, but unused for another  level. 

As a result, I want to remove the `-r` argument from the mission application service, and instead, create an optional `start_on_boot` flag in the `manifest.toml` file that allows you to declare that the app should be started on boot.

**Comment by marshall** [comment]
FWIW, the only reason an argument isn't used for the `OnCommand` run level is because that is the default run level :)

In any case, I agree that an app should either start on boot or be commanded opportunistically, probably not both. I agree with your suggestion, and maybe we should take it a bit further andget rid of the `run level` concept all together since there will only 1 run-level left if the option is moved to `config.toml`

**Comment by jacoffey3** [comment]
Yeah that's what I'm proposing is removing run level altogether. There will be no "Run Level", there will just be the flag in the manifest if you want it to start on boot. 

This will also be useful, because when we get to the [scheduler](https://github.com/kubos/kubos/issues/336), we will be able to have a new section in the manifest that allows you to add a schedule for the app.
